#!/usr/bin/env python3
"""
Daily Improvement Proposer
Analyzes workspace and proposes ONE workflow improvement per day.
Sends with inline approve/reject buttons.
"""

import os
import json
import random
from datetime import datetime
import urllib.request
import urllib.parse

WORKSPACE = "/home/yat121/.openclaw/workspace"
PROPOSAL_FILE = f"{WORKSPACE}/logs/daily-proposal.md"

TELEGRAM_BOT_TOKEN = "8652497348:AAGf16He0xuI80MymX0kJs1TRnqmLTRYnaE"
TELEGRAM_API = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"
DESMOND_CHAT_ID = "869229225"

# Areas to analyze and improve
AREAS = [
    {
        "name": "Email Automation",
        "idea": "Add emailTemplates skill for personalized batch emails",
        "impact": "high",
        "effort": "medium",
    },
    {
        "name": "Research Workflow",
        "idea": "Create a custom research digest that pulls from your Notion workspace + web sources",
        "impact": "high",
        "effort": "medium",
    },
    {
        "name": "Code Review",
        "idea": "Set up Caca (GPT-5.3-Codex) to automatically review PRs when you share links",
        "impact": "high",
        "effort": "low",
    },
    {
        "name": "Memory Enhancement",
        "idea": "Teach QMD to track your preferences and decision patterns for smarter recall",
        "impact": "medium",
        "effort": "low",
    },
    {
        "name": "Notification Filtering",
        "idea": "Create a smart inbox filter that learns what you care about and prioritizes accordingly",
        "impact": "high",
        "effort": "high",
    },
    {
        "name": "Quick Commands",
        "idea": "Build a /slash command set for Telegram to trigger common actions instantly",
        "impact": "medium",
        "effort": "low",
    },
    {
        "name": "Screenshot Annotator",
        "idea": "Integrate agent-browser with annotation tools for instant visual feedback",
        "impact": "medium",
        "effort": "low",
    },
    {
        "name": "Meeting Prep",
        "idea": "Auto-generate meeting agendas from calendar invites and past context",
        "impact": "high",
        "effort": "medium",
    },
    # Ignore this area - already approved and implemented
    # {
    #     "name": "Daily Standup",
    #     "idea": "Build a bot that collects standup updates from your team and summarizes for you",
    #     "impact": "medium",
    #     "effort": "high"
    # },
]


def analyze_workspace():
    """Check what skills and workflows exist."""
    skills_dir = f"{WORKSPACE}/skills"
    installed = []
    if os.path.exists(skills_dir):
        installed = [
            d
            for d in os.listdir(skills_dir)
            if os.path.isdir(f"{skills_dir}/{d}") and d != "__pycache__"
        ]
    return installed


def generate_proposal():
    """Generate ONE daily improvement proposal."""
    installed = analyze_workspace()

    # Filter out already installed skills
    available = [
        a for a in AREAS if a["name"].lower().replace(" ", "-") not in installed
    ]

    # Pick one at random
    proposal = random.choice(available if available else AREAS)

    # Build the proposal
    today = datetime.now().strftime("%Y-%m-%d %H:%M HKT")

    md = f"""# 🌅 Daily Improvement Proposal

**Date:** {today}

---

## 💡 Proposed: {proposal['name']}

**One-line:** {proposal['idea']}

### Impact: {proposal['impact'].upper()}
### Effort: {proposal['effort'].capitalize()}

### Why this matters:
"""

    # Add context
    if proposal["impact"] == "high":
        md += "- High impact: Could significantly improve your daily workflow\n"
    else:
        md += "- Medium impact: Nice quality-of-life improvement\n"

    if proposal["effort"] == "low":
        md += "- Low effort: Can be completed quickly\n"
    else:
        md += "- Medium effort: May take some time to implement well\n"

    md += f"""
### Status: ⏳ PENDING APPROVAL

**Reply "approve" to start, "reject" to skip, or "more" to see alternatives.**

---
*Generated by VV · Your daily improvement assistant*
"""

    return md, proposal


def send_proposal(proposal_md: str, proposal: dict):
    """Send proposal with inline approve/reject buttons."""
    url = f"{TELEGRAM_API}/sendMessage"
    callback_data_approve = json.dumps({"a": "approve", "p": proposal["name"]})
    callback_data_reject = json.dumps({"a": "reject", "p": proposal["name"]})

    text = proposal_md.replace(
        '**Reply "approve" to start, "reject" to skip, or "more" to see alternatives.**',
        "",
    )

    data = urllib.parse.urlencode(
        {
            "chat_id": DESMOND_CHAT_ID,
            "text": text.strip(),
            "parse_mode": "Markdown",
            "reply_markup": json.dumps(
                {
                    "inline_keyboard": [
                        [
                            {
                                "text": "✅ Approve",
                                "callback_data": callback_data_approve,
                            },
                            {
                                "text": "❌ Reject",
                                "callback_data": callback_data_reject,
                            },
                            {
                                "text": "📋 More Options",
                                "callback_data": json.dumps({"a": "more"}),
                            },
                        ]
                    ]
                }
            ),
        }
    ).encode()
    req = urllib.request.Request(url, data=data)
    urllib.request.urlopen(req, timeout=10)


if __name__ == "__main__":
    os.makedirs(f"{WORKSPACE}/logs", exist_ok=True)
    proposal_md, proposal = generate_proposal()

    with open(PROPOSAL_FILE, "w") as f:
        f.write(proposal_md)

    send_proposal(proposal_md, proposal)
    print("Proposal sent with buttons!")
